'use strict';
/* ============================================================
 * AI-generated raster sprites.
 *
 * Loads PNGs from assets/ (described by assets/manifest.js,
 * generated by dev/imagegen/) and offers them to Sprites.get()
 * as drop-in replacements. Entirely optional: when the manifest
 * or an image is missing — or we run headless — callers fall
 * back to the procedural art.
 * ============================================================ */

const Assets = (() => {
  const entries = {};   // asset key -> {c, w, h, oy, chimney, lights, ready}
  const textures = {};  // grass|sand|water|deep|rock -> {img, size, ready}
  let enabled = false;

  // manifest texture keys -> terrain names used by sprites.js
  const TEX_NAMES = { tex_grass: 'grass', tex_sand: 'sand', tex_water: 'water', tex_deep: 'deep', tex_rock: 'rock' };

  /* Map the game's sprite keys onto generated asset keys. */
  function assetKeyFor(key) {
    const m = key.match(/^house(\d):(\d)$/);
    if (m) return `house${m[1]}_${parseInt(m[2], 10) % 2}`;
    if (/^tree\d$/.test(key)) return 'tree' + (parseInt(key.slice(4), 10) % 4);
    if (/^rock\d$/.test(key)) return 'rock' + (parseInt(key.slice(4), 10) % 2);
    return key;
  }

  /* Sprite lookup; returns null when the raster art can't serve this key. */
  function get(key) {
    if (!enabled) return null;
    const night = key.endsWith('@n');
    const base = night ? key.slice(0, -2) : key;
    const e = entries[assetKeyFor(base)];
    if (!e || !e.ready) return null;
    if (!night) return e;
    if (!e.nightC) { // lazy blue-tinted night variant
      try {
        const c = document.createElement('canvas');
        c.width = e.c.naturalWidth; c.height = e.c.naturalHeight;
        const x = c.getContext('2d');
        x.drawImage(e.c, 0, 0);
        x.globalCompositeOperation = 'source-atop';
        x.fillStyle = 'rgba(38,48,92,0.28)';
        x.fillRect(0, 0, c.width, c.height);
        e.nightC = { c, w: e.w, h: e.h, oy: e.oy, chimney: null, lights: [] };
      } catch (err) {
        e.nightC = e; // tinting unavailable — reuse the day sprite
      }
    }
    return e.nightC;
  }

  function texture(name) {
    if (!enabled) return null;
    const t = textures[name];
    return t && t.ready ? t : null;
  }

  function init() {
    if (typeof Image === 'undefined' || typeof ASSET_MANIFEST === 'undefined') return;
    // resolve assets/ relative to this script so dev/*.html pages work too
    let root = 'assets/';
    try {
      const cur = document.currentScript && document.currentScript.src;
      if (cur) root = cur.replace(/js\/assets\.js.*$/, '') + 'assets/';
    } catch (err) { /* keep default */ }

    for (const key in (ASSET_MANIFEST.objects || {})) {
      const m = ASSET_MANIFEST.objects[key];
      const img = new Image();
      const e = { c: img, w: m.w, h: m.h, oy: m.oy, chimney: null, lights: [], ready: false, nightC: null };
      img.onload = () => { e.ready = true; };
      img.src = root + m.file;
      entries[key] = e;
    }
    for (const key in (ASSET_MANIFEST.textures || {})) {
      const name = TEX_NAMES[key];
      if (!name) continue;
      const m = ASSET_MANIFEST.textures[key];
      const img = new Image();
      const t = { img, size: m.size, ready: false };
      img.onload = () => { t.ready = true; };
      img.src = root + m.file;
      textures[name] = t;
    }
    enabled = true;
  }

  init();
  return { get, texture, enabled: () => enabled };
})();
